-- CREATE MONTH COLUMN
WITH FT_TRAFFIC_WITH_MONTH AS (
  SELECT *, CEILING(INSTALLMENT_KEY / 100) AS MONTH
  FROM FT_TRAFFIC
)

-- COMPUTE ELAPSED PLAYTIME BY USER BY GAME WITHIN MONTH
WITH PLAYER_PLAYTIMES_BY_MONTH AS (
  SELECT MONTH, PLAYER_KEY, INSTALLMENT_KEY, MAX(PLAYTIME_VALUE) - MIN(PLAYTIME_VALUE) AS PLAYTIME
  FROM FT_TRAFFIC_WITH_MONTH
  GROUP BY MONTH, PLAYER_KEY, INSTALLMENT_KEY
)

-- TABLE WITH GAMES WHICH DO NOT CONTAIN BETA OR TEST
WITH PRODUCTION_GAMES AS (
  SELECT INSTALLMENT_DESCRIPTION
  FROM DIM_INSTALLMENT
  WHERE INSTALLMENT_DESCRIPTION NOT LIKE '%beta%'
  OR INSTALLMENT_DESCRIPTION NOT LIKE '%test%'
)

-- GET AGGREGATION BY COUNTRY AND BY GAME.
-- ONLY KEEP GAMES WHERE TOTAL AMOUNT OF TIME SPENT BY PLAYERS IS LESS THAN 10 HOURS
-- ONLY KEEP GAMES WHO DO NOT CONTAIN 'beta' or 'test'
WITH COUNTRY_PLAYTIME_BY_MONTH AS (
  SELECT MONTH, COUNTRY_CD, INSTALLMENT_DESCRIPTION, SUM(PLAYTIME) AS PLAYTIME
  FROM PLAYER_PLAYTIMES_BY_MONTH AS P
  INNER JOIN DIM_PLAYER AS D ON P.PLAYER_KEY = D.PLAYER_KEY
  INNER JOIN PRODUCTION_GAMES AS PG ON P.INSTALLMENT_DESCRIPTION = PG.INSTALLMENT_DESCRIPTION
  WHERE PLAYTIME / 60 < 10
  GROUP BY MONTH, COUNTRY_CD, INSTALLMENT_DESCRIPTION
  ORDER BY MONTH DESC, PLAYTIME
)

-- WHAT IS MISSING: FILTERING THE TOP 100 GAMES
